version: '3.8'
services:
  # api_1:
  #   container_name: datn_api_1
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - REDIS_HOST=cache
  #     - CACHE_PORT=6379
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - '${PORT}:${PORT}'
  #   depends_on:
  #     - db
  #     - cache
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  cache:
    container_name: datn_cache
    image: redis:6.2
    ports:
      - '${CACHE_PORT}:6379'
    volumes:
      - type: volume
        source: redis-data
        target: /data
  db:
    container_name: datn_database
    image: mysql:8.0.23
    platform: linux/x86_64
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_DB_PORT}:3306'
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  mysql-data:
    name: datn-database-mysql-volume
  redis-data:
    name: datn-cache-redis-volume
